version: 2.1

commands:
  sayhello:
    description: "デモ用のコマンド"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  myJob:
    parameters:
      to:
        type: string
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - sayhello:
          to: << parameters.to >>

workflows:
  myWorkflow:
    jobs:
      - myJob:
          to: "params from workflow"