version: 2.1

parameters:
  run_my_workflow:
    type: boolean
    default: false

commands:
  sayhello:
    description: "デモ用のコマンドだよ"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  myJob:
    parameters:
      to:
        type: string
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - sayhello:
          to: << parameters.to >>

workflows:
  normalWorkflow:
    jobs:
      - myJob:
          to: "from normal workflow..."
  specialWorkflow:
    when: << pipeline.parameters.run_my_workflow >>
    jobs:
      - myJob:
          to: "from special workflow!!"