version: 2.1
jobs:
  helloWorld:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run:
        name: "はろーわーるどすてっぷ"
        command: echo "はろーわーるど"
workflows:
  welcome:
    jobs:
      - helloWorld