version: 2.1

commands:
  sayhello:
    description: "デモ用のコマンド"
    parameters:
      to:
        type: string
        defualt: "Hello World"
    steps:
      - run: echo << parameters.to >>

jobs:
  myjob:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - sayhello
      - sayhello:
          to: "Override params"